### ISSUE TITLE
Consider rebasing on a newer, currently-supported Electron release

### ISSUE THREAD

**Issue by anh0516** [PC7-Client/PC7-Client#4]
When running the current v9.3.0 from the commandline, it reports
```
    - electron@10.4.7
    - nodejs@12.16.3
    - Chromium@85.0.4183.121
```
Electron 10.4.7, based on Chromium 85, was the last release in the Electron 10 series. It was [EOLed on May 5, 2021](https://releases.electronjs.org/releases/stable?version=10), over 3 years ago.

Rebasing on a newer Electron release will improve both performance and security. It will also allow support for Wayland on Linux, which will improve input latency for Wayland users vs. running under XWayland as it is now.

**Comment by AceSilentKill** [comment]
The outdated version of Electron used in PC7 was chosen deliberately. Chromium versions later than the one bundled in electron 10.4.7 make the game unplayable for users on Windows, which accounts for around 95% of our userbase. Chromium prioritizes mouse inputs over WebSockets on higher versions. Unfortunately this has forced us, and many other electron-based IO game clients to use this older version. If this were not the case, we would definitely be using an newer version.

https://github.com/6ct/mouse-freeze-bug
